# Generated by Django 3.1 on 2020-08-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutual_fund_name', models.CharField(max_length=256)),
                ('investment_amount', models.IntegerField(blank=True, null=True)),
                ('investment_date', models.DateField()),
                ('units', models.IntegerField(blank=True, null=True)),
                ('withdraw_amount', models.FloatField(blank=True, null=True)),
                ('withdraw_date', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
